version: '3.4'

networks:
    internal:
        external: false
    nm:
        external: true

services:
    nginx:
        image: nginx:latest
        networks:
            - internal
            - nm
        ports:
            - "80:80"
        volumes:
            - .:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs:/var/log/nginx/
        depends_on:
            - php
        restart: unless-stopped
        container_name: nm_nginx

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                - NOVA_USERNAME=${NOVA_USERNAME}
                - NOVA_PASSWORD=${NOVA_PASSWORD}
        user: "1000:33"
        networks:
            - internal
            - nm
        volumes:
            - .:/var/www/
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        restart: unless-stopped
        container_name: nm_php

    postgres:
        image: library/postgres:12.3
        networks:
            - internal
            - nm
        volumes:
            - ./pgsql_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGGSSENCMODE=disable
        ports:
            - "5432:5432"
        restart: unless-stopped
        container_name: nm_postgres
